TRUNCATE results_category RESTART IDENTITY CASCADE;
INSERT INTO results_Category(category, category_description) VALUES ('1.1', 'Eendaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('2.1', 'Meerdaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('2.1s', 'Etappe 2.1 koers');
INSERT INTO results_Category(category, category_description) VALUES ('1.HC', 'Eendaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('1.WT1', 'Eendaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('1.WT2', 'Eendaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('1.WT3', 'Eendaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('2.HC', 'Meerdaagse koers');
INSERT INTO results_Category(category, category_description) VALUES ('2.HCs', 'Etappe');
INSERT INTO results_Category(category, category_description) VALUES ('2.WT1', 'Klassiekers als RVV, PR, MSR');
INSERT INTO results_Category(category, category_description) VALUES ('2.WT1s', 'Etappe');
INSERT INTO results_Category(category, category_description) VALUES ('2.WT2', 'Klassiekers niveau 2: AGR, Waalse Pijl');
INSERT INTO results_Category(category, category_description) VALUES ('2.WT2s', 'Etappe');
INSERT INTO results_Category(category, category_description) VALUES ('2.WT3', 'Mindere eendagskoersen van hoogste UCI niveau');
INSERT INTO results_Category(category, category_description) VALUES ('2.WT3s', 'Etappe');
INSERT INTO results_Category(category, category_description) VALUES ('NC1', 'Nationaal Kampioenschap hoogste niveau');
INSERT INTO results_Category(category, category_description) VALUES ('NC2', 'Nationaal Kampioenschap niveau 2');
INSERT INTO results_Category(category, category_description) VALUES ('NC3', 'Nationaal Kampioenschap niveau 3');
INSERT INTO results_Category(category, category_description) VALUES ('NC4', 'Nationaal Kampioenschap niveau 4');
INSERT INTO results_Category(category, category_description) VALUES ('NC5', 'Nationaal Kampioenschap niveau 5');
INSERT INTO results_Category(category, category_description) VALUES ('NCT1', 'Nationaal Kampioenschap tijdrijden niveau 1');
INSERT INTO results_Category(category, category_description) VALUES ('NCT2', 'Nationaal Kampioenschap tijdrijden niveau 2');
INSERT INTO results_Category(category, category_description) VALUES ('NCT3', 'Nationaal Kampioenschap tijdrijden niveau 3');
INSERT INTO results_Category(category, category_description) VALUES ('NCT4', 'Nationaal Kampioenschap tijdrijden niveau 4');
INSERT INTO results_Category(category, category_description) VALUES ('NCT5', 'Nationaal Kampioenschap tijdrijden niveau 5');
INSERT INTO results_Category(category, category_description) VALUES ('GT1', 'Tour de France eindklassement');
INSERT INTO results_Category(category, category_description) VALUES ('GT1s', 'Etappe GT1');
INSERT INTO results_Category(category, category_description) VALUES ('GT1r', 'Berg- en Puntenklassement GT1');
INSERT INTO results_Category(category, category_description) VALUES ('GT2', 'Giro en Vuelta');
INSERT INTO results_Category(category, category_description) VALUES ('GT2s', 'Etappe GT2');
INSERT INTO results_Category(category, category_description) VALUES ('GT2r', 'Berg- en Puntenklassement GT2');
INSERT INTO results_Category(category, category_description) VALUES ('CC1', 'Continental Championship, niveau 1. EK');
INSERT INTO results_Category(category, category_description) VALUES ('CC2', 'Continental Championship, niveau 2');
INSERT INTO results_Category(category, category_description) VALUES ('CCT1', 'Continental Championship Tijdrijden, niveau 1. EK');
INSERT INTO results_Category(category, category_description) VALUES ('CCT2', 'Continental Championship Tijdrijden, niveau 2. Aziatisch, Afrikaans kampioenschap.');
INSERT INTO results_Category(category, category_description) VALUES ('WCRR', 'WK op de weg');
INSERT INTO results_Category(category, category_description) VALUES ('WCTT', 'WK tijdrijden');
