# Generated by Django 3.0.7 on 2020-12-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='updated',
        ),
    ]
