# Generated by Django 4.0 on 2022-01-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualteam',
            options={'ordering': ['-editie', '-price'], 'verbose_name_plural': 'Virtual Teams'},
        ),
    ]
