# Generated by Django 3.0.7 on 2020-12-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0002_remove_bid_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamCaptainStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.IntegerField(default=0)),
                ('amount_left', models.IntegerField(default=100)),
                ('riders_needed', models.IntegerField(default=9)),
                ('max_allowed_bid', models.IntegerField(default=92)),
                ('team_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
