# Generated by Django 4.0 on 2022-01-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_virtualteam_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualteam',
            old_name='ploegleider',
            new_name='team_captain',
        ),
    ]
