# Generated by Django 3.0.7 on 2021-01-23 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0001_initial'),
        ('auction', '0003_tobeauctioned_verkocht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobeauctioned',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='results.Rider'),
        ),
    ]
