# Generated by Django 3.0.7 on 2020-12-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('auction', '0003_auto_20201229_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCaptain',
            fields=[
                ('team_size', models.IntegerField(default=0)),
                ('amount_left', models.IntegerField(default=100)),
                ('riders_needed', models.IntegerField(default=9)),
                ('max_allowed_bid', models.IntegerField(default=92)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamCaptainStatus',
        ),
    ]
