# Generated by Django 4.0 on 2022-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_rename_ploegleider_virtualteam_team_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualteam',
            name='punten',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
