# Generated by Django 3.0.7 on 2021-01-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20210123_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tobeauctioned',
            old_name='verkocht',
            new_name='sold',
        ),
    ]
