# Generated by Django 3.0.7 on 2021-12-05 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0002_auto_20211205_2133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0005_auto_20210123_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcaptain',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tobeauctioned',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tobeauctioned',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.Rider'),
        ),
        migrations.AlterField(
            model_name='virtualteam',
            name='editie',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AlterUniqueTogether(
            name='tobeauctioned',
            unique_together={('team_captain', 'rider')},
        ),
    ]
