# Generated by Django 3.0.7 on 2020-12-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('results', '0007_rider_sold'),
        ('auction', '0005_tobeauctioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.Rider')),
                ('team_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
