# Generated by Django 3.0.7 on 2021-12-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20211205_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tobeauctioned',
            options={'ordering': ['modified']},
        ),
        migrations.AddField(
            model_name='tobeauctioned',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
