# Generated by Django 3.0.7 on 2021-01-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0008_delete_verkocht'),
        ('auction', '0006_joker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcaptain',
            options={'ordering': ['-amount_left', '-user']},
        ),
        migrations.CreateModel(
            name='VirtualTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editie', models.PositiveIntegerField(default=2021)),
                ('price', models.IntegerField(default=0)),
                ('punten', models.FloatField(default=0)),
                ('jpp', models.IntegerField(default=0)),
                ('ploegleider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.TeamCaptain')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.Rider')),
            ],
            options={
                'verbose_name_plural': 'Sold riders',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Verkocht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editie', models.PositiveIntegerField(default=2021)),
                ('price', models.IntegerField(default=0)),
                ('punten', models.FloatField(default=0)),
                ('jpp', models.IntegerField(default=0)),
                ('ploegleider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.TeamCaptain')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.Rider')),
            ],
            options={
                'verbose_name_plural': 'Verkochte renners',
                'ordering': ['-price'],
            },
        ),
    ]
