# Generated by Django 3.0.7 on 2021-12-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20211206_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tobeauctioned',
            options={'ordering': ['order', 'modified']},
        ),
        migrations.AddField(
            model_name='tobeauctioned',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
