# Generated by Django 3.0.7 on 2021-01-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20210101_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tobeauctioned',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='name',
            field=models.CharField(default='naam invoeren', max_length=30),
        ),
        migrations.AlterField(
            model_name='bid',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.TeamCaptain'),
        ),
        migrations.AlterField(
            model_name='joker',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.TeamCaptain'),
        ),
        migrations.AlterField(
            model_name='tobeauctioned',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.TeamCaptain'),
        ),
        migrations.DeleteModel(
            name='Verkocht',
        ),
        migrations.AddField(
            model_name='auctionorder',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.TeamCaptain'),
        ),
    ]
