# Generated by Django 3.0.7 on 2021-01-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20210104_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcaptain',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='teamcaptain',
            name='amount_left',
        ),
        migrations.RemoveField(
            model_name='teamcaptain',
            name='max_allowed_bid',
        ),
        migrations.RemoveField(
            model_name='teamcaptain',
            name='riders_needed',
        ),
        migrations.RemoveField(
            model_name='teamcaptain',
            name='team_size',
        ),
    ]
