# Generated by Django 4.0 on 2021-12-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auctionorder_team_captain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionorder',
            options={'ordering': ['riders_proposed', 'order']},
        ),
        migrations.AlterField(
            model_name='auctionorder',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.teamcaptain'),
        ),
        migrations.AlterField(
            model_name='joker',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.teamcaptain'),
        ),
        migrations.AlterField(
            model_name='tobeauctioned',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.teamcaptain'),
        ),
        migrations.AlterField(
            model_name='virtualteam',
            name='ploegleider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.teamcaptain'),
        ),
    ]
