# Generated by Django 4.0 on 2021-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auctionorder_team_captain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcaptain',
            options={'ordering': ['riders_proposed', 'order']},
        ),
        migrations.RenameField(
            model_name='teamcaptain',
            old_name='user',
            new_name='team_captain',
        ),
        migrations.RemoveField(
            model_name='teamcaptain',
            name='name',
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='riders_proposed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AuctionOrder',
        ),
    ]
